plugins {
    id("java-common-conventions")
}

repositories {
    mavenCentral()
}
dependencies {

    implementation platform('software.amazon.awssdk:bom:2.27.21')
    implementation 'software.amazon.awssdk:s3'

    testImplementation 'org.springframework.boot:spring-boot-webmvc-test'
    implementation project(':web')
    implementation project(':infra')
    implementation project(':service')
}