spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: 'root'
    password: '00000000'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379


jude:
  field:
    username: email
    password: password
  auth:
    default-url: /api/v1/auth
    login-url: /login
    logout-url: /logout